[[ -f $HOME/.bashrc ]] && . $HOME/.bashrc
[[ -f $HOME/.profile ]] && . $HOME/.profile

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/calvin/Code/google-cloud-sdk/path.bash.inc' ]; then source '/Users/calvin/Code/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/calvin/Code/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/calvin/Code/google-cloud-sdk/completion.bash.inc'; fi
