# Add MacPorts packages to PATH.
if [ `uname` == "Darwin" ]; then
    PATH=/opt/local/libexec/gnubin:/opt/local/bin:/opt/local/sbin:/opt/local/lib/postgresql92/bin:$PATH
fi

[[ -f $HOME/.bashrc ]] && . $HOME/.bashrc
[[ -f $HOME/.profile ]] && . $HOME/.profile
