#!/usr/bin/env bash

# Check for an interactive session
[ -z "$PS1" ] && return

# Ignore duplicates in bash_history
HISTCONTROL=ignoreboth

# Ignore these commands in history file
HISTIGNORE=ls:ll:la:pwd:exit:df:clear

# Append to the bash history file, rather than overwriting it
shopt -s histappend

# Disable Ctrl+S to suspend terminal
stty -ixon

# ------------------------
# Environment variables
# ------------------------

# Set default text editor
export EDITOR="vim"

# Silence OSX message about making ZSH the default shell.
export BASH_SILENCE_DEPRECATION_WARNING=1

# Set PATH to include user's bin dir if it exists
if [ -d "$HOME/.bin" ]; then
    export PATH="$HOME/.bin:$PATH"
fi

# Add Homebrew packages to PATH.
if [ `uname` == "Darwin" ]; then
    export PATH="/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/libpq/bin:/usr/local/sbin:$PATH"
fi

# Enable bash completion
[ -f /usr/local/etc/bash_completion ] && source /usr/local/etc/bash_completion

# Set up Go.
export GOPATH=$HOME/Code/go
export PATH="$PATH:$GOPATH/bin"

# Set up pyenv.
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

# Set up NVM.
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"

# Enable direnv.
eval "$(direnv hook bash)"

# Need this in order to install anything that requires zlib on Catalina.
# Source: https://akrabat.com/installing-pillow-on-macos-10-15-calatalina/
export CPATH=`xcrun --show-sdk-path`/usr/include

# ------------------------
# Prompt
# ------------------------
# Virtualenv prompt info
function virtualenv_prompt_info {
    [[ $VIRTUAL_ENV ]] && echo "[$(basename $VIRTUAL_ENV)] "
}

# Git prompt info
function parse_git_dirty {
  [[ -n $(git status -s ${SUBMODULE_SYNTAX}  2> /dev/null) ]] && echo "*"
}
function git_prompt_info {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || \
  ref=$(git rev-parse --short HEAD 2> /dev/null) || return
  echo "(${ref#refs/heads/}$(parse_git_dirty))"
}

# Color bash prompt
export PS1='\[\033[01;32m\]\u@\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\] $(virtualenv_prompt_info)\[\033[01;33m\]$(git_prompt_info)\[\033[00m\]
$ '
export SUDO_PS1='\[\033[01;31;40m\]\u@\h \[\033[00m\]\w
$ '

# ------------------------
# Aliases
# ------------------------
# Must use the `--` operator in order to bind an alias to `-`
alias -- -="cd -"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias ls="ls -F --color=auto"
alias la="ls -alh"
alias grep="grep --color=auto"
alias e="emacsclient -t"
alias ipython="ipython --colors Linux"

alias di="docker images"
alias dstopall='docker stop $(docker ps -a -q)'
function dclean() {
    docker rm -v $(docker ps --all --quiet --filter "status=exited")
    docker rmi $(docker images --filter "dangling=true" --quiet)
}

# Colorize man pages.
man() {
    env \
	LESS_TERMCAP_md=$'\e[1;34m' \
	LESS_TERMCAP_me=$'\e[0m' \
	LESS_TERMCAP_se=$'\e[0m' \
	LESS_TERMCAP_so=$'\e[1;40;92m' \
	LESS_TERMCAP_ue=$'\e[0m' \
	LESS_TERMCAP_us=$'\e[1;32m' \
	man "$@"
}

# Enable fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
